---
# - hosts: all
#   become: true
#   tasks:
   - name: pull an image
     docker_image:
       name: syntropynet/agent:stable
       force: yes

   - name: Stop and remove old container
     docker_container:
       name: syntropy-agent
       state: absent
       image: syntropy-agent

   - name: Create Syntropy agent container and connect to network
     docker_container:
       name: syntropy-agent
       restart_policy: unless-stopped
       image: syntropynet/agent:stable
       network_mode: "host"
       purge_networks: no
       env:
         SYNTROPY_API_KEY: '{{ api_key }}'
         SYNTROPY_NETWORK_API: docker
         SYNTROPY_PROVIDER: '{{ cloud_provider }}'
         SYNTROPY_TAGS: '{{ inventory_hostname }}'
         SYNTROPY_AGENT_NAME: '{{ inventory_hostname }}'
       volumes:
       - /var/run/docker.sock:/var/run/docker.sock:ro
       devices:
       - "/dev/net/tun:/dev/net/tun"
       capabilities:
       - net_admin
       - sys_module
